#!/usr/bin/env python3
"""Convert WAV files to a C header with PCM arrays for the Clawdmeter firmware.

Reads stereo/mono WAV files, mixes to mono, keeps the original sample rate,
and outputs 16-bit signed PCM as PROGMEM C arrays.
"""
import struct
import sys
import wave
from pathlib import Path

SOUNDS = [
    ("snd_stop",        "SND_STOP.wav"),
    ("snd_fail",        "SND_STOP_FAILURE.wav"),
    ("snd_perm_req",    "SND_PERMISSION_REQUEST.wav"),
    ("snd_perm_prompt", "SND_PERMISSION_PROMPT.wav"),
    ("snd_idle",        "SND_IDLE_PROMPT.wav"),
    ("snd_task_done",   "SND_TASK_COMPLETEDwav.wav"),
]


def wav_to_mono_pcm(path: str) -> tuple[list[int], int]:
    """Read a WAV, mix to mono 16-bit, return (samples, sample_rate)."""
    w = wave.open(path, "rb")
    nch = w.getnchannels()
    sw = w.getsampwidth()
    sr = w.getframerate()
    raw = w.readframes(w.getnframes())
    w.close()

    samples = []
    if sw == 2:
        fmt = f"<{len(raw)//2}h"
        all_samples = struct.unpack(fmt, raw)
        if nch == 2:
            for i in range(0, len(all_samples), 2):
                samples.append((all_samples[i] + all_samples[i + 1]) // 2)
        else:
            samples = list(all_samples)
    elif sw == 1:
        # 8-bit unsigned → 16-bit signed
        for b in raw:
            samples.append((b - 128) * 256)
        if nch == 2:
            mono = []
            for i in range(0, len(samples), 2):
                mono.append((samples[i] + samples[i + 1]) // 2)
            samples = mono
    else:
        raise ValueError(f"Unsupported sample width: {sw}")

    return samples, sr


def emit_array(name: str, samples: list[int]) -> str:
    lines = [f"static const int16_t {name}[] PROGMEM = {{"]
    row = []
    for s in samples:
        row.append(f"{s:6d}")
        if len(row) == 16:
            lines.append("    " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ",".join(row))
    lines.append("};")
    lines.append(f"static const size_t {name}_len = {len(samples)};")
    return "\n".join(lines)


def main():
    wav_dir = sys.argv[1] if len(sys.argv) > 1 else "/Users/bernardo/Downloads/sounds"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "sound_data.h"

    header = """#pragma once
// Auto-generated by tools/generate_sounds.py — do not edit.
// 16-bit signed mono PCM.
#include <stdint.h>
#include <stddef.h>
#include <pgmspace.h>
"""

    sample_rate = None
    total_bytes = 0

    for name, filename in SOUNDS:
        path = str(Path(wav_dir) / filename)
        samples, sr = wav_to_mono_pcm(path)
        if sample_rate is None:
            sample_rate = sr
        elif sr != sample_rate:
            print(f"WARNING: {filename} has {sr} Hz, expected {sample_rate} Hz")

        total_bytes += len(samples) * 2
        dur = len(samples) / sr
        print(f"  {name}: {len(samples)} samples ({len(samples)*2/1024:.1f} KB, {dur:.2f}s) @ {sr} Hz")
        header += "\n" + emit_array(name, samples) + "\n"

    header += f"""
#define SOUND_SAMPLE_RATE {sample_rate}

enum sound_id_t {{
    SND_STOP,
    SND_STOP_FAILURE,
    SND_PERMISSION_REQUEST,
    SND_PERMISSION_PROMPT,
    SND_IDLE_PROMPT,
    SND_TASK_COMPLETED,
    SND_COUNT,
}};

struct SoundEntry {{
    const int16_t* data;
    size_t length;
}};

static const SoundEntry sound_table[SND_COUNT] = {{
    {{ snd_stop,        snd_stop_len        }},
    {{ snd_fail,        snd_fail_len        }},
    {{ snd_perm_req,    snd_perm_req_len    }},
    {{ snd_perm_prompt, snd_perm_prompt_len }},
    {{ snd_idle,        snd_idle_len        }},
    {{ snd_task_done,   snd_task_done_len   }},
}};
"""

    with open(out_path, "w") as f:
        f.write(header)

    print(f"\nGenerated {out_path}: {len(SOUNDS)} sounds, {total_bytes/1024:.1f} KB total @ {sample_rate} Hz")


if __name__ == "__main__":
    main()
